export const DOCUMENT_CODES = {
  NOT_FOUND: "DOCUMENT_NOT_FOUND",
  PDF_TOO_LARGE: "PDF_TOO_LARGE",
  PDF_CORRUPTED: "PDF_CORRUPTED",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  EMBEDDING_FAILED: "EMBEDDING_FAILED",
  PROCESSING_TIMEOUT: "PROCESSING_TIMEOUT",
} as const;
